---
apiVersion: v1
kind: Secret
metadata:
  name: freenas-nfs
  namespace: kube-system
type: Opaque
stringData:
  # note that all values are relative to where the provisioner is running
  # ie: if running the provisioner directly on the FreeNAS server 'localhost'
  # would be a valid 'host' value

  # http|https
  # default: http
  #protocol: 

  # default: localhost (for running the provisioner out of cluster directly on FreeNAS node)
  #host: 

  # default: 80
  #port: 

  # default: root (api is only available for root currently)
  #username: 
  password:

  # allow for self-signed/untrusted certs if using https
  # true|false
  # default: false
  #allowInsecure: 
